import type { ChatBotConfig } from '../types';

const dslInterfaceContext = [
  'DSL/Main.hs authoring guide',
  '',
  'Code-generation behavior',
  '',
  '- Treat this guide as the stable public DSL contract and the supplied artefact',
  '  as the current source of truth. Make only the requested, in-scope edits and',
  '  preserve unrelated working code.',
  '- Use only helpers exported by the public facade. If the requested behavior is',
  '  not expressible by the documented API, explain the limitation rather than',
  '  inventing an import, constructor, or helper.',
  '- Before returning a source update, check the public export contract, payload',
  '  types, linear ownership flow, materialization paths, and visual selectors.',
  '  Return the complete updated source in `sourceArtifactContent` when a DSL',
  '  change is requested; otherwise return no source artefact.',
  '',
  'Public module contract',
  '',
  '- Keep the module name `DSL.Main`.',
  '- Export `example :: Choreography ()`; this is the editable algorithm/program',
  '  whose execution becomes the trace.',
  '- Export `run :: Choreography () -> VisualTraceGraph`; build it with',
  '  `runChoreographyWith $ visualize $ do`.',
  '- Import the public `LinearTrace.Choreography` facade. Do not reach into',
  '  `LinearTrace.Core.*` or view implementation modules for ordinary DSL work.',
  '- Preserve the `NoImplicitPrelude`, `LinearTypes`, `RebindableSyntax`,',
  '  `OverloadedLabels`, and related language-extension/linear-Prelude pattern',
  '  already established by `Main.hs`.',
  '',
  'Linear trace and type discipline',
  '',
  '- `Choreography a` is a linear trace builder. A `Block tag` is an opaque,',
  '  linearly owned live resource of the phantom type `tag`; every block must be',
  '  consumed exactly once by the type-safe lifecycle below.',
  '- Declare semantic phantom tags (`data Value`, `data Match`, etc.) and map each',
  '  tag to a public payload representation with a type instance such as',
  '  `type instance Payload Value = LInt Value`.',
  '- The supported payload wrappers are `LUnit`, `LBool`, `LInt`, `LDouble`,',
  '  `LString`, and `LOperator`. `Traceable tag` is available when the associated',
  '  payload is a core payload and the tag is typeable.',
  '- Define `CoreOperator` for custom operator values: provide readable operator',
  '  text and linear persistence. Define `Applicable1` or `Applicable2` with an',
  '  associated `Apply1Result`/`Apply2Result` and `applyPayload1`/`applyPayload2`',
  '  when an operation consumes typed payloads and produces a typed result.',
  '- Use `applyLinear1`, `applyLinear1Into`, `applyLinear2`, or',
  '  `applyLinear2Into` to implement linear payload transformations; do not unwrap',
  '  or duplicate linear values by ordinary non-linear helpers.',
  '- `create payload` allocates a pending value and returns `Create pending`.',
  '  A `Pending tag` is not a live block and must be finished with `materialize`,',
  '  `materializeWithTags`, or `commit` before it can be used.',
  '- `materialize query pending` creates a live `Block tag` and attaches semantic',
  '  facts from the query to its trace snapshot. `commit` is the untagged alias for',
  '  materialization; use the tagged form whenever a value should be selectable in',
  '  the visualization.',
  '- `copy block` consumes the input handle and returns `Copy original pending`:',
  '  keep `original` for the continuing computation and materialize the pending',
  '  copy for a probe, branch, or temporary view.',
  '- `replace block pending` consumes the old block and replacement pending value;',
  '  materialize the replacement to record a mutation while retaining one live',
  '  replacement block.',
  '- `apply1 operator argument` and `apply2 operator lhs rhs` consume all operand',
  '  blocks and return typed pending results. Materialize the result before using',
  '  or selecting it.',
  '- `use block` consumes a block and returns `Use (OneUse payload)`. Pattern-match',
  '  `OneUse` exactly once to inspect a value or branch; the consumed block cannot',
  '  be referenced again.',
  '- `destroy block` consumes a block and closes its lifetime. Recursively destroy',
  '  every remaining block in lists/records and destroy resources in both branches as',
  '  appropriate; never leave a live block hidden in a returned structure.',
  '- `checkpoint "label"` closes the current batch of trace events into a named',
  '  algorithm stage. Add checkpoints after creation, comparisons, branches,',
  '  mutations, exhaustion, and completion so the timeline explains state change.',
  '- Use linear pattern matching, recursion, and explicit ownership-passing data',
  '  types (`Block tag %1`) to make state transitions visible and compiler-checked.',
  '  Never use `unsafeCoerce`, ordinary containers that duplicate blocks, or a',
  '  non-linear alias for a live resource.',
  '',
  'How trace facts become visual nodes',
  '',
  '- A materialized block snapshot contains its typed payload, lifecycle event',
  '  provenance, and `Facts`. The facts are the stable semantic address used by',
  '  the visualization layer; visual rules match facts, not generated numeric IDs',
  '  or source-code line numbers.',
  '- Give every visual-worthy value a meaningful path at materialization, for',
  '  example `#target <&> #source`, `#array <&> #index index`,',
  '  `#result <&> payload True`, or `#array <&> #processed`.',
  '- `#label` creates an atom query with `OverloadedLabels`; compose paths with',
  '  `<&>`. Use `@: i` to insert a dynamic `QueryInt` (usually from `bindInt`) so',
  '  repeated elements retain stable indexed identities.',
  '- For programmatic queries, use `emptyQuery`, `queryAtom`, `queryInt`,',
  '  `queryAppend`, and `queryIndex`; prefer overloaded labels for readable',
  '  semantic paths. The low-level `Facts`/`factAtom`/`factSymbol`/`factInt`',
  '  vocabulary is available when a query needs to be assembled explicitly.',
  '- `materializeWithTags baseQuery selectQuery pending` adds a base path and',
  '  payload-dependent facts. Use it when the payload value itself determines a',
  '  semantic branch, label, category, or dynamic binding.',
  '- `payload` creates a typed payload pattern. Use `payload True`/`False`, numeric',
  '  or string literals to match a value, or `payload v` where `v` is a',
  '  `bindContent` binding to capture the value for content or a query. Use',
  '  `select @AnyPayload query` only when the tag is intentionally irrelevant.',
  '- A trace operation is visible through the snapshots it emits: create/copy/',
  '  replace/apply results become pending events when materialized, while use and',
  '  destroy record their consumed snapshots. Attach facts consistently to the',
  '  relevant source, probe, result, and updated blocks so a visual rule can follow',
  '  the complete value lineage over time.',
  '',
  'Visual selection, grouping, and detail',
  '',
  '- In `run`, `select @Tag query` returns a typed `Selected tag` binding inside a',
  '  `VisualizationBuilder`. The rule applies to every matching trace snapshot,',
  '  including repeated algorithm iterations, so write reusable rules rather than',
  '  one rule per occurrence.',
  '- `select @AnyPayload query` matches any traceable payload at the query path.',
  '  Prefer the typed form because it preserves payload-specific matching and',
  '  makes invalid visual associations fail at compile time.',
  '- `node selected` groups selected trace nodes into a synthetic container. Render',
  '  and constrain the group for a row/cluster/background, then select its children',
  '  for individual detail. Grouping is the right way to express membership and',
  '  relative layout without inventing node IDs.',
  '- `render selected recipe` attaches all visual detail to the matched trace',
  '  selection. A recipe may contain:',
  '  - `content "literal"` for fixed text, or `content v` for a `bindContent`',
  '    value captured from the matched payload.',
  '  - `style @Field value` for typed style fields: `Opacity`, `ZIndex`, `Padding`,',
  '    `FontSize`, `Radius`, `StrokeWidth`, `Alpha`, `Fill`, `Stroke`,',
  '    `FontFamily`, `FontWeight`, `FontStyle`, `TextAlign`, `WhiteSpace`, and',
  '    `BorderStyle`.',
  '  - `width`, `height`, `top`, `left`, `right`, `bottom`, `x`, and `y` to assign',
  '    solver-backed geometry. `bounds` and `center` are convenient compound',
  '  forms; `size` reads the selected node width/height pair.',
  '- Use separate selections and renders for semantic sub-states, e.g.',
  '  `#result`, `#result <&> payload True`, and',
  '  `#result <&> payload False`, so the same trace result can have a neutral',
  '  container and branch-specific `MATCH`/`NO MATCH` content and styling.',
  '- `bindContent` captures a matched payload as display text; `bindInt` captures',
  '  an indexed query value for labels, repeated-element queries, and symbolic',
  '  layout bindings. Bindings are substituted per match, so avoid hard-coding',
  '  values that should follow the trace.',
  '- `style @Fill`/`@Stroke` take colors such as `Hsl hue saturation lightness`;',
  '  scalar fields take the appropriate `Span`, `Unit`, or `Free` value. Use',
  '  `FixedStyle` for deterministic categorical values and `VariableStyle` with',
  '  `choice` for solver-selected categorical variation. `styleOf` reads a',
  '  selected field when a relation should be based on existing visual detail.',
  '- Treat the trace query as the source of visual identity: if a node needs a',
  '  label, color, shape, or status, add a semantic fact/payload pattern at the',
  '  trace boundary and match it in `run`. Do not key visual rules by list order,',
  '  block numbers, or incidental compiler output.',
  '',
  'Solver-backed layout and relations',
  '',
  '- Layout values are typed symbolic expressions: `Coord` for positions,',
  '  `Span` for sizes/gaps, `Offset` for differences, and `Scalar` for unitless',
  '  scale factors. Construct constants with `at`, `by`, and `shift`; use',
  '  `asCoord`/`asSpan` when converting an offset and use `+`, `-`, `*`, `/`, and',
  '  `|+|` only where their dimensional types permit.',
  '- `variable @Span` creates a fresh solver variable; `variableFrom expression`',
  '  creates a derived symbolic value. Use `global "name"` only for deliberate',
  '  shared variables. `choice @FontFamily` (or another choice domain) creates a',
  '  categorical solver choice.',
  '- Read selected geometry with `x`, `y`, `left`, `right`, `top`, `bottom`,',
  '  `width`, and `height`, then relate selections rather than assigning fixed',
  '  coordinates. For example, `bottom a =| gap |= top b` expresses a gap between',
  '  rows and `x a .==. x b` aligns their centers.',
  '- `ensure` emits a hard constraint; use `.<=.`, `.>=.`, and `.==.` for numeric',
  '  relations. `encourage` emits a soft preference that the solver may relax.',
  '  Use `=|`/`|=` for directed edge-to-edge gaps and `=/`/`/=` for symmetric or',
  '  non-equality relations where appropriate.',
  '- Keep constraints relative, reusable, and attached to semantic selections.',
  '  Bound dimensions to sensible ranges and use soft preferences for aesthetics;',
  '  do not encode a single fixed coordinate layout when the same rule should work',
  '  for different inputs or solver seeds.',
  '',
  'General visualization authoring rules',
  '',
  '- Model algorithm state, comparisons, branch outcomes, ownership changes,',
  '  mutations, and completion as typed linear trace events and named checkpoints.',
  '- Materialize with semantic facts at each point that the front end may need to',
  '  display or compare across revisions. The visual layer should then derive',
  '  labels, grouping, style, and geometry from those facts and payload patterns.',
  '- Preserve the complete linear lifecycle of every value while adding visual',
  '  detail: visualizing a copy must not consume the original, and displaying a',
  '  payload must not bypass `use` when the algorithm needs to inspect it.',
  '- Keep the program layer independent from the visual layer: `example` describes',
  '  the computation and trace; `run` describes how matching trace facts become a',
  '  visual graph. Prefer adding a semantic fact or typed tag over coupling the two',
  '  layers through ad hoc names.'
].join(String.fromCharCode(10));

export default {
  id: 'ai-assistant',
  initialPrompt:
    'Answer the user. If they request a DSL change, return the complete updated compile/app/DSL/Main.hs source in sourceArtifactContent; otherwise return null for that field. Treat the artifact context as authoritative and do not invent omitted revisions.',
  buildContext: ({ artifact }) => ({
    dslInterface: dslInterfaceContext,
    artifact
  }),
  parameters: {
    model: 'gpt-5.6',
    reasoningEffort: 'medium',
    maxOutputTokens: 4096
  },
  responseFormat: {
    name: 'chat_result',
    strict: true,
    schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        reply: { type: 'string' },
        sourceArtifactContent: {
          anyOf: [{ type: 'string' }, { type: 'null' }]
        }
      },
      required: ['reply', 'sourceArtifactContent']
    }
  }
} satisfies ChatBotConfig;
